#! /bin/sh

xdo kill $(xdo id -N Polybar)
i=0
monitors=$(bspc query -M --names)
for monitor in $monitors; do
    MONITOR="$monitor" polybar panel &
    i=$((i + 1))
done
if [ $i -eq 1 ]; then
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
else
    monitor1=$(echo $monitors | cut -d ' ' -f 1)
    monitor2=$(echo $monitors | cut -d ' ' -f 2)
    bspc monitor "$monitor2" -d 1 2 3 4 5 6 7 8 9
    bspc monitor "$monitor1" -d 0
    bspc monitor "$monitor1" -s "$monitor2"
    bspc monitor "$monitor2" -f
fi

bspc config border_width         4
bspc config window_gap           12

sh ~/.config/bspwm/commands.sh theme --set

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
