#! /bin/sh

sxhkd &
~/.config/bspwm/panel &
xdo lower $(xdo id -a panel)

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           12

bspc config normal_border_color '#808080'
bspc config focused_border_color '#3585ce'
bspc config presel_feedback_color '#3585ce'

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
